dask/dask-ml

- daskml/preprocessing/__init__.py
- daskml/preprocessing/data.py
- docs/source/modules/api.rst
- tests/preprocessing/test_data.py
This mimics the scikit-learn implementation. The primary difference is that our
version uses *apporiximate* quantiles. I suspect this is a good default for
daskml. It'd be nice to implement an exact version as well, though I'll wait for
interest from users first.
Benchmark:
```python
In [1]: import numpy as np
...: import dask.array as da
...:
...: import sklearn.preprocessing as pp
...: import daskml.preprocessing as dp
...:
...: X = da.random.random(size=(10_000_000, 10), chunks=1_000_000)
...: x = X.compute()
...:
...: qt = pp.QuantileTransformer()
...: dqt = dp.QuantileTransformer()
...:
In [2]: %time qt.fit(x)
CPU times: user 5.92 s, sys: 961 ms, total: 6.88 s
Wall time: 7.01 s
Out[2]:
QuantileTransformer(copy=True, ignore_implicit_zeros=False, n_quantiles=1000, …
```
> ENH: Added QuantileTransformer

- dask_ml/cluster/_k_means.pyx
Setup:
```python
import numpy as np
from pandas.util.testing import test_parallel
from dask_ml.cluster.k_means import _centers_dense
class KMeansBench:
goal_time = 0.5
def setup(self):
rng = np.random.RandomState(0)
n_samples = 1000000
n_features = 30
n_clusters = 15
X = rng.uniform(size=(n_samples, n_features)).astype('f4')
labels = rng.randint(0, n_clusters, size=n_samples).astype('i4')
distances = np.empty(shape=(n_samples,), dtype='f4')
self.X = X
self.labels = labels
self.distances = distances
self.n_clusters = n_clusters
@test_parallel(num_threads=4)
def time_centers_dense(self):
_centers_dense(self.X, self.labels, self.n_clusters, self.distances)
bench = KMeansBench()
bench.setup()
```
Master:
```python
%timeit bench.time_centers_dense()
81 ms ± 792 µs per loop (mean ± std. dev. of …
```
> PEF: Nogil for _centers_dense

- setup.py
We don't actually use it anywhere in the library
> PKG: Don't depend on distributed

- setup.py
One of my absolute paths was leaking into the SOURCES.txt, causing conda-build to fail. I think this will remedy the problem.
xref: https://github.com/conda-forge/staged-recipes/pull/4229 and https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.18080/job/ad1n0ghbpabrk0c9
> Use relative path in setup.py

- dask_ml/datasets.py
- docs/source/glm.rst
Also, I found that this example failed:
```python
>>> from dask_ml.linear_model import LogisticRegression
>>> from dask_ml.datasets import make_classification
>>> X, y = make_classification()
>>> lr = LogisticRegression()
>>> lr.fit(X, y)
```
Chunks wasn't available in the `_wrap_maker` function, presumably because I didn't provide it as a keyword to `make_classification`.  Is this a requirement?  If so, how should I adjust the example?
> Refer to dask_ml over dask_glm in docs

- ci/environment-27.yml
- ci/environment.yml
- dask_ml/cluster/k_means.py
- dask_ml/metrics/pairwise.py
- dask_ml/utils.py
- tests/test_kmeans.py
Comes from trying to satisfy check_estimator. But that seems a bit
too restrictive.
> Various k-means fixes

- dask_ml/preprocessing/data.py
- dask_ml/utils.py
- docs/source/changelog.rst
- docs/source/conf.py
- docs/source/contributing.rst
- docs/source/index.rst
- tests/preprocessing/test_data.py
- tests/test_utils.py
Closes #75 
I've (temporarily) removed the `columns` argument. I'm going to come back with another PR handling it generically for many transformers.
> API: Have concrete values for fitted attributes

- dask_ml/decomposition/__init__.py
- dask_ml/decomposition/pca.py
- dask_ml/decomposition/truncated_svd.py
- dask_ml/utils.py
- docs/source/modules/api.rst
- tests/test_pca.py
- tests/test_svd.py
- tests/test_utils.py
> [WIP]TruncatedSVD/PCA

- pyproject.toml
- setup.py
Adds a pyproject.toml to allow building from source without Cython already in the environment.
This relies on pip>=10.0, which isn't released yet, though it looks like they're close. I'd rather just merge this PR and instruct users to install Cython manually before installing dask-ml, rather than complicate our setup.py further. Once pip 10 is out and supporting PEP-518, things should work fine (and it does work for me locally with pip 10).
Closes #92 
cc @metasyn
> BLD: Added pyproject.toml

- dask_ml/preprocessing/__init__.py
- dask_ml/preprocessing/data.py
- docs/source/changelog.rst
- docs/source/modules/api.rst
- docs/source/preprocessing.rst
- tests/preprocessing/test_data.py
This is adding an OrdinalEncoder (or integer encoder) that basically just converts the categorical columns into its integer codes (eg for trees).
There is quite some overlap with the code in DummyEncoder, so I could create a common base class. But first wanted to have something working.
> ENH: Ordinal (integer) Encoding

- dask_ml/base.py
- tests/linear_model/test_stochastic_gradient.py
This makes `model.score` more robust to types (and resolves an issue I had).
> MAINT: check if matrix is an ndarray in predict

- dask_ml/_partial.py
- dask_ml/wrappers.py
- docs/source/changelog.rst
- docs/source/incremental.rst
- docs/source/modules/api.rst
- tests/linear_model/test_neural_network.py
- tests/linear_model/test_passive_aggressive.py
- tests/linear_model/test_perceptron.py
- tests/linear_model/test_stochastic_gradient.py
- tests/test_blockwise.py
- tests/test_incremental.py
- tests/test_minibatch.py
- tests/test_naive_bayes.py
Adds a meta-estimator for wrapping estimators that implement `partial_fit`.
```python
In [1]: from dask_ml.wrappers import Blockwise
...: from dask_ml.datasets import make_classification
...: import sklearn.linear_model
...:
...:
In [2]: X, y = make_classification(chunks=25)
In [3]: est = sklearn.linear_model.SGDClassifier()
In [4]: clf = Blockwise(est, classes=[0, 1])
In [5]: clf.fit(X, y)
Out[5]:
Blockwise(estimator=SGDClassifier(alpha=0.0001, average=False, class_weight=None, epsilon=0.1,
eta0=0.0, fit_intercept=True, l1_ratio=0.15,
learning_rate='optimal', loss='hinge', max_iter=None, n_iter=None,
n_jobs=1, penalty='l2', power_t=0.5, random_state=None,
shuffle=True, tol=None, verbose=0, warm_start=False))
```
A few notes:
1. The name: I went with `Blockwise`. We could also do …
> Blockwise Metaestimator

- dask_ml/_partial.py
- dask_ml/_utils.py
- dask_ml/metrics/__init__.py
- dask_ml/metrics/classification.py
- dask_ml/metrics/regression.py
- dask_ml/metrics/scorer.py
- dask_ml/wrappers.py
- docs/source/incremental.rst
- tests/conftest.py
- tests/metrics/test_classification.py
- tests/metrics/test_regression.py
- tests/test_datasets.py
- tests/test_incremental.py
Closes https://github.com/dask/dask-ml/issues/195
Summary of changes
1. ``**kwargs`` in the Incremental constructor now refers to hyperparameters
of `estimator`, rather than fit_kwargs
2. fit_kwargs are now passed in `fit`.
This *seemed* to work just fine with `sklearn.model_selection.GridSearchCV`.
Incremental.fit is correctly getting Dask (not NumPy) arrays.
Will try it out on a larger test now.
> ENH: Make Incremental work in grid search

- dask_ml/metrics/__init__.py
- dask_ml/metrics/scorer.py
- dask_ml/wrappers.py
- tests/test_incremental.py
I specified a `scoring` keyword arg to `Incremental` and ran into a bug: if I specified a `scoring` keyword arg, then an if-statement in `get_scorer` wasn't working or tested. This resolves that.
The tests primarily test to make sure no errors are thrown.
> TST: test the scoring kwarg for Incremental

- dask_ml/_partial.py
- tests/test_partial.py
I was just exploring the code and noticed the occurrence of reblock in
https://github.com/dask/dask/blob/master/dask/array/learn.py#L71
https://github.com/dask/dask/blob/master/dask/array/learn.py#L101
... I looked for the implementation and couldn't find any, and later found out that it was replaced with rechunk.
See: https://github.com/dask/dask/pull/3570
> fix: outstanding occurrences of reblock replaced with rechunk

- dask_ml/model_selection/_split.py
- tests/model_selection/test_split.py
Fixes #215.
I ran into this while creating an example for https://github.com/dask/dask-searchcv/pull/72 that required the 20 newsgroups dataset. This is the easiest fix.
> MAINT: revert back to sklearn's train_test_split if not all dask arrays

- docs/source/conf.py
Currently pull request links formatted like `` :pr:`<number>` `` aren't rendered correctly in the docs (e.g. the changelog). This PR adds to `extlinks` in `conf.py` for these pull request links.
> Fix PR links

- dask_ml/metrics/scorer.py
- tests/test_incremental.py
This PR makes `check_scoring` return a callable as mentioned in the sklearn docs: http://scikit-learn.org/dev/modules/generated/sklearn.metrics.check_scoring.html. It returns the sklearn's `check_scoring` unless we've implemented it.
It also does two other maintenance items:
* Actually performs `assert` (gosh, did I really make that typo?)
* Gets rid of `FutureWarning`s from `SGDClassifier` by specifying `tol=1e-3`.
> MAINT: properly impelment check_scoring

- dask_ml/_compat.py
- dask_ml/compat.py
- dask_ml/metrics/classification.py
- docs/source/changelog.rst
- tests/metrics/test_classification.py
This PR adds implements sample weighting for `accuracy_score`
> Adds sample weights to accuracy_score

- dask_ml/preprocessing/__init__.py
- dask_ml/preprocessing/label.py
- docs/source/changelog.rst
- docs/source/modules/api.rst
- docs/source/preprocessing.rst
- tests/metrics/test_classification.py
- tests/preprocessing/test_label.py
This PR adds `LabelEncoder` as a drop-in replacement for `sklearn.preprocessing.LabelEncoder`.
> Adds LabelEncoder

- docs/source/examples/tensorflow.ipynb
The current tf example code doesn't quite work as-is.  It also uses the outdated "channel" approach which dask now uses queues for.  This is a tiny change to bring things up to working order.
> Replaced channels with queues and other misc. cleanup.

- dask_ml/wrappers.py
- tests/test_incremental.py
Two changes:
1. Modify `ParallelPostFit` to accepts score ndarrays if passed by using sklearn's `get_scorer`.
2. Move the logic in #236 to `Incremental.fit` (which works because `partial_fit` calls `fit`).
> MAINT: ndarrays for score (and move ndarray logic from partial_fit to fit)

- ci/environment-2.7.yml
- ci/environment-3.6.yml
This reverts commit 0030863513386320531de6ffd27e85aee39fcecd.
[ci skip]
We use matplotlib elsewhere.
> Revert "Remove sphinx gallery from env" [ci skip]

- dask_ml/_partial.py
Closes #261 
With this I've seen a speedup of about 2x for my example notebook in https://github.com/dask/dask-examples/pull/15, which is supported by the dask dashboard profiling graph.
> MAINT: remove tokenize in partial_fit

- dask_ml/_compat.py
- dask_ml/compat.py
- dask_ml/model_selection/_compat.py
- dask_ml/model_selection/_search.py
- tests/model_selection/dask_searchcv/test_model_selection.py
- tests/model_selection/dask_searchcv/test_model_selection_sklearn.py
This PR consolidates `dask_ml/_compat.py`, `dask_ml/compat.py`, and the newly added `dask_ml/model_selection/_compat.py` modules into a single `dask_ml/_compat.py` file. 
Closes #242
> Consolidates compat modules

- dask_ml/model_selection/_search.py
- tests/model_selection/dask_searchcv/test_model_selection.py
This removes the _normalize_scheduler function from dask_searchcv and
some of the scheduling names (threaded, sequential) and replaces them
with the Dask logic.
This both unifies logic across projects and also lets the distributed
scheduler take over when it is set as default.
Fixes https://github.com/dask/dask-ml/issues/249
> Use default scheduler sniffing logic from dask

- dask_ml/preprocessing/data.py
- tests/preprocessing/test_data.py
This changes some tests so that assert_eq accepts dask objects rather
than numpy ones.  This allows us to perform a variety of useful checks
like `x.dtype == x.compute().dtype`.
> Avoid calling compute prior to assert_eq in tests

- dask_ml/_partial.py
- dask_ml/wrappers.py
- tests/test_incremental.py
- tests/test_partial.py
Closes #274.
A screenshot of different `partial_fit` calls:
| Before (almost) | After |
|:--:|:--:|
|<img width="609" alt="screen shot 2018-07-03 at 11 06 04 am" src="https://user-images.githubusercontent.com/1320475/42329630-ac187c3a-8060-11e8-84c5-cc7aaad365be.png"> | <img width="624" alt="screen shot 2018-07-03 at 1 07 36 pm" src="https://user-images.githubusercontent.com/1320475/42237033-2bddf11e-7eec-11e8-88c5-5f0ebd2fb4df.png"> |
I only show the before for some comparison, though it's not exact (and was in the debug process). It is "almost" because it uses a fixed seed every time, not a random seed. It does not run through the blocks in sequential order as mentioned in the previous docs.
> MAINT: randomly sample chunks for partial_fit calls

- ci/install-circle.sh
- setup.py
This PR adds `packaging` to `install_requires` in `setup.py`. Closes #290.
> Adds packaging requirement to setup.py

- docs/source/examples.rst
And a little reformatting to make the links more clear.
> DOC: link to dask-examples on examples page

- docs/source/incremental.rst
Closes https://github.com/dask/dask-ml/issues/289
In local testing with an RTD docker image, I noticed that the `gs.fit(X, y, classes[0, 1])`  line took a long time. This will hopefully fix things.
> DOC: Smaller Incremental examples

- dask_ml/preprocessing/label.py
- docs/source/contributing.rst
- docs/source/preprocessing.rst
- tests/preprocessing/test_label.py
Enhances LabelEncoder to use CategoricalDtype for pandas and dask
series.
This improves the performance, and will be helpful for implementing OneHotEncoder efficiently for dask dataframes.
```python
import string
import numpy as np
import pandas as pd
import dask.dataframe as dd
import dask_ml.preprocessing
dtype = pd.api.types.CategoricalDtype(list(string.ascii_letters[:12]))
n = 1_000_000
data = dd.from_pandas(
pd.Series(np.random.choice(dtype.categories, size=n), dtype=dtype),
npartitions=n // 100_000
)
```
Setup
```python
le = dask_ml.preprocessing.LabelEncoder()  # True / False
codes = le.fit_transform(data)
print('fit')
%timeit le.fit(data)
print('transform')
%timeit le.transform(data)
print('transform-compute')
%timeit le.transform(data).compute()
print('inverse_transform')
%timeit …
```
> ENH: LabelEncoder supports pandas Categorical

- setup.py
`toolz` was missing as a dependency in the `setup.py` `install_requires`
list.
fixes issue #304
> Add `toolz` as a dependency for pip install

- benchmarks/k_means_kdd.py
- benchmarks/kmeans_airline.py
- dask_ml/cluster/k_means.py
- dask_ml/utils.py
- dask_ml/wrappers.py
> Add utilities functions to time functions

- dask_ml/model_selection/methods.py
- dask_ml/model_selection/utils.py
- dask_ml/model_selection/utils_test.py
- dask_ml/utils.py
- docs/source/changelog.rst
- setup.cfg
- tests/model_selection/dask_searchcv/test_model_selection.py
- tests/test_utils.py
This is an incorrect fix for #319.
Hadcoding `list` as the only arraylike thing that isn't sent through `_indexable` isn't right, but I'm not sure what else should be exempted. Mainly because I don't yet understand  the purpose of `to_indexable`.
cc @jcrist do you have any thoughts here?
Closes #319
> Don't pack every list-like fit param

- dask_ml/feature_extraction/text.py
- dask_ml/model_selection/__init__.py
- dask_ml/model_selection/_incremental.py
- dask_ml/model_selection/_search.py
- dask_ml/wrappers.py
- docs/source/examples/text-vectorization.ipynb
- docs/source/hyper-parameter-search.rst
- docs/source/incremental.rst
- docs/source/modules/generted/dask_ml.compose.ColumnTransformer.rst
- docs/source/modules/generted/dask_ml.compose.make_column_transformer.rst
- tests/model_selection/test_incremental.py
Here's a rough draft of what a base class calling `_incremental.fit` may look like. I've just been stealing pieces from https://github.com/dask/dask-ml/pull/221 and making it work for the random sampler with the `remove_worst` strategy.
Looking at #221 there were a few pieces that will be common to each subclass
* data checking
* CV splitting
* building cv_results (partly)
* selecting the best model (partly)
That leaves a few things that must be done by each class
* Building the dict of `{model_id: (param_list, additional_calls)}`
* transforming the output of `fit` on each of those into a common form
In the end, I'm not sure how much code reuse we'll actually get, but I think it's worth exploring a bit further. A next step would be to make a branch of #221 that builds on top of this, and …
> Base class for estimators using _incremental.fit

- dask_ml/compose/__init__.py
- dask_ml/compose/_column_transformer.py
This PR adds a scikit-learn version check to only add `ColumnTransformer` to the `dask_ml.compose` namespace if `ColumnTransformer` is present in `sklearn` (i.e. `sklearn` version >= `0.20.0.dev0`). 
For example, currently `dask_ml` will still attempt to import `ColumnTransformer` when using v0.19.1 of scikit-learn: 
```python
In [1]: import sklearn
In [2]: sklearn.__version__
Out[2]: '0.19.1'
In [3]: from dask_ml.compose import ColumnTransformer
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-037f94f5147b> in <module>()
----> 1 from dask_ml.compose import ColumnTransformer
~/github/dask/dask-ml/dask_ml/compose/__init__.py in <module>()
16 # del parse
17
---> 18 from …
```
> Adds sklearn version check for ColumnTransformer import

- ci/environment-2.7.yml
- ci/environment-3.6.yml
- dask_ml/_compat.py
- dask_ml/compose/__init__.py
- dask_ml/compose/_column_transformer.py
- dask_ml/impute.py
- dask_ml/metrics/pairwise.py
- dask_ml/model_selection/_search.py
- dask_ml/model_selection/utils.py
- dask_ml/preprocessing/__init__.py
- dask_ml/preprocessing/_encoders.py
- docs/source/changelog.rst
- setup.cfg
- setup.py
- tests/compose/test_column_transformer.py
- tests/metrics/test_metrics.py
- tests/model_selection/dask_searchcv/test_model_selection.py
- tests/model_selection/dask_searchcv/test_model_selection_sklearn.py
- tests/preprocessing/test_encoders.py
- tests/test_impute.py
- tests/test_parallel_post_fit.py
Closes #391 
Closes #383
Closes #384 
Subsumes #389
> Bump sklearn min version to 0.20

- dask_ml/cluster/k_means.py
- tests/test_kmeans.py
Fixes #390 
I went with the easier approach of just forcing chunk lengths.  I did this after I realized that we're going to be doing multiple passes anyway.
> Support dataframes for k-means

- dask_ml/_partial.py
- tests/test_partial.py
Previously these functions would fail on dask dataframes.
Now they coerce to dask arrays, and predict also converts back
I'm not sure if this logic is also handled elsewhere.  I was running into it with the criteo example though.
> Support dataframes in _partial.py::fit/predict

- dask_ml/wrappers.py
- tests/test_parallel_post_fit.py
This still needs a test.  I tried modifying `tests/test_parallel_post_fit.py::test_auto_rechunk` but that didn't trigger the failure.  
```diff
diff --git a/tests/test_parallel_post_fit.py b/tests/test_parallel_post_fit.py
index e3e7096..2d3d079 100644
--- a/tests/test_parallel_post_fit.py
+++ b/tests/test_parallel_post_fit.py
@@ -1,6 +1,7 @@
import dask
import dask.array as da
import dask.dataframe as dd
+import numpy as np
import pytest
import sklearn.datasets
from sklearn.decomposition import PCA
@@ -119,3 +120,8 @@ def test_auto_rechunk():
assert clf.predict(X).compute().shape == (1000,)
assert clf.predict_proba(X).compute().shape == (1000, 2)
assert clf.score(X, y) == clf.score(X.compute(), y.compute())
+
+    X, y = make_classification(n_samples=1000, n_features=20, chunks=100)
+ …
```
> Don't use auto chunking with unknown chunk sizes

- dask_ml/feature_extraction/text.py
- dask_ml/wrappers.py
Previously we would pass around Estimator.predict methods.  These methods are
opaque to serialization heuristics used in dask.distributed that are used to
determine what should move and how to serialize it.
Now we pass around bare functions that take in estimators as parameters.
> Pass models in predict rather than their methods

- dask_ml/metrics/scorer.py
- dask_ml/wrappers.py
- tests/test_incremental.py
- tests/test_parallel_post_fit.py
I notice that we are not consistent in the various `score` methods in our classes.  Some of them are lazy, some of them are immediate.  None of them support a `compute=` keyword. 
All of the others are trivial to add a `compute=` keyword, what should the default be?  True or False?
> Allow compute=False in ParallelPostFit.score

- dask_ml/preprocessing/__init__.py
- dask_ml/preprocessing/data.py
- docs/source/modules/api.rst
- docs/source/preprocessing.rst
- tests/preprocessing/test_data.py
At the current stage the pull request implements PolynomialFeatures in dask-ml for dask arrays with known shape and chunk size.
Implements Issue #347
> [MRG] Poly trans: Issue #347

- dask_ml/model_selection/_incremental.py
- tests/model_selection/test_incremental.py
A couple issues when given a small grid.
For the first, we decided that training 0 models was best, as `inverse(next_time_step)` was 0.
For the second, we got stuck in an infinite `while True` loop since
1. `inverse(current_time_step) == inverse(next_time_step)` was always equal (both were 0), and
2. next_time_step is increasing.
We could detect this and raise when something like `start < current_time_step + 1`, but ideally we would support this. I'm not sure that my fix is correct though.
> IncrementalSearch edge cases

- dask_ml/model_selection/__init__.py
- dask_ml/model_selection/_incremental.py
- docs/source/hyper-parameter-search.rst
- tests/model_selection/test_incremental.py
The PR makes 4 improvements to the incremental search API:
* renames `IncrementalSearch` to `IncrementalSearchCV`
* renames `history_results_` to `history_`
* adds `cv_results_` to mirror Scikit-learn's `RandomizedSearchCV`
* returns all model information from `_incremental.fit`
* which is implemented as `model_history_` in `IncrementalSearchCV`
* allow `incremental._fit` to return multiple models
* in `IncrementalSearchCV`, choose the best among those models.
> API: improve and clean IncrementalSearch API

- dask_ml/model_selection/_incremental.py
- tests/model_selection/test_incremental.py
This avoids the loop, and hopefully does the correct thing.
IIUC, `decay=0` should be "just keep training all the models".
> Avoid infinite loop in IncrementalSearchCV with decay=0

- ci/environment-2.7.yml
- ci/environment-3.6.yml
- dask_ml/model_selection/_search.py
- dask_ml/preprocessing/data.py
- tests/linear_model/test_stochastic_gradient.py
- tests/model_selection/dask_searchcv/test_model_selection.py
- tests/test_incremental.py
- tests/test_partial.py
This PR removes an occurrences of the `get=` keyword in `dask-ml`
Related to error in #417
> Remove get= keyword

- dask_ml/linear_model/glm.py
This PR makes a few of minor changes to the `_GLM` base estimator. Namely: 
- Adds `max_iter` parameter to the docstring
- Renames the `multiclass` keyword to `multi_class` to match the corresponding scikit-learn keyword (ref: [scikit-learn's LogisticRegression](http://scikit-learn.org/dev/modules/generated/sklearn.linear_model.LogisticRegression.html)). Even though this keyword is currently ignored in dask-ml, I still think it's worth being consistent with scikit-learn. 
- Moves the position of the `max_iter` keyword the `_GLM.__init__` signature to have the same order as scikit-learn.
> Minor glm updates

- dask_ml/model_selection/_split.py
Small fix for #428, which confused me as well
> Fix typo in train_test_split docstring

- docs/source/changelog.rst
> fix typo: model_selectoin -> model_selection

- dask_ml/_partial.py
Currently we're passing a dictionary `values` method to `sharedict.merge` instead of the actual values themselves. Fixes #454.
> Fix incremental bug with Dask sharedict

- ci/environment-2.7.yml
- ci/environment-3.6.yml
This PR adds both the system and Python `graphviz` package to the dev environment for dask-ml. `graphviz` is needed for building the documentation. Closes #457.
> Add graphviz to dev environment

- tests/preprocessing/test_data.py
Theses tests were asserting that you could train on a dataframe and transform an array.
I don't really know how these worked in the past. Pandas and numpy unfortunately have different broadcasting behavior (which pandas is working to fix).
```python
In [16]: x
Out[16]:
array([[ 1.2061934 ,  0.78132208],
[ 0.14763367, -0.47647038],
[ 0.37784154,  1.13200053],
[ 1.58888898, -1.84890062]])
In [17]: s
Out[17]:
0    1.206193
1    0.781322
dtype: float64
In [18]: x * s.values
Out[18]:
array([[ 1.45490252,  0.61046419],
[ 0.17807476, -0.37227683],
[ 0.45574998,  0.88445701],
[ 1.9165074 , -1.44458687]])
In [19]: x * s
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last) …
```
> remove failing tests

- dask_ml/cluster/k_means.py
- dask_ml/preprocessing/data.py
**Context**:
- in `dask`, `da.atop` has been replace by `da.blockwise` defined in the same scope — see [dask source](https://github.com/dask/dask/blob/master/dask/array/blockwise.py#L203) ;
- in `cluster.KMeans`, warnings are thrown because `da.atop` is used ;
**Changes proposed:**
- replace `da.atop` by `da.blockwise` to remove those warnings ;
> Change `da.atop` that has been replaced by `da.blockwise` in 

- .circleci/config.yml
- ci/environment-2.7.yml
- ci/environment-3.6.yml
- dask_ml/__init__.py
- dask_ml/_compat.py
- dask_ml/cluster/__init__.py
- dask_ml/cluster/k_means.py
- dask_ml/cluster/spectral.py
- dask_ml/linear_model/__init__.py
- dask_ml/metrics/__init__.py
- dask_ml/model_selection/__init__.py
- dask_ml/model_selection/_incremental.py
- dask_ml/model_selection/_search.py
- dask_ml/model_selection/_split.py
- dask_ml/model_selection/methods.py
- dask_ml/preprocessing/__init__.py
- dask_ml/preprocessing/_encoders.py
- dask_ml/preprocessing/data.py
- dask_ml/preprocessing/label.py
- setup.py
- tests/compose/test_column_transformer.py
- tests/preprocessing/test_encoders.py
This PR adds a CircleCI job to run our tests against the oldest supported version of our dependencies. Closes #456.
> Add CI job for oldest supported dependencies

- .gitignore
This PR adds `pip-wheel-metadata/` and `.pytest_cache/` to our `.gitignore`
> Minor updates to .gitignore

- dask_ml/preprocessing/_encoders.py
- dask_ml/preprocessing/data.py
- tests/preprocessing/test_data.py
- tests/preprocessing/test_encoders.py
There are a couple of recent updates to scikit-learn `master` that are causing the `sklearn_dev` CI build to fail (ref https://circleci.com/gh/dask/dask-ml/3634?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link). The recent changes are:
- `drop=` keyword was added to `OneHotEncoder` in https://github.com/scikit-learn/scikit-learn/pull/12908
- Internals of `QuantileTransformer` where updated in https://github.com/scikit-learn/scikit-learn/pull/12827
To fix these failures, this PR:
- Adds a `drop=` keyword to the `dask_ml.preprocessing.OneHotEncoder`. By default `drop=None`, which maintains the current behavior. For now, a `NotImplementedError` error is raised when `drop` is not `None`. I also added a test to ensure `NotImplementedError` is raised …
> Fix sklearn dev tests

- dask_ml/cluster/spectral.py
- dask_ml/linear_model/glm.py
- dask_ml/model_selection/_incremental.py
- dask_ml/model_selection/_search.py
- dask_ml/model_selection/methods.py
- dask_ml/preprocessing/_encoders.py
The new release of `isort` (version 4.3.10) changed how relative import sorting is handled. This PR makes updates to have v4.3.10 of `isort` pass.
> Fix imports for isort 4.3.10

- dask_ml/wrappers.py
In the https://ml.dask.org/modules/generated/dask_ml.wrappers.Incremental.html#dask_ml.wrappers.Incremental there is a link which redirects to scikit learn scaling strategies page when you click the list of incremental learners and it is not working anymore and  I updated the new link.
> Issue 478 fix -- Documentation link error

- dask_ml/_partial.py
- tests/test_incremental.py
This PR makes sure that dataframes work with Incremental. For tests, I modify the basic incremental test and pass both Dask arrays and dataframes.
**Reference issues/PRs**
* #220: "Verify Incremental works with dask.dataframe"
* #454: I found this issue while writing https://github.com/dask/dask-ml/issues/454#issuecomment-463258586
* #456, which is on setting minimum dependency versions for CI jobs
> TST: make sure Incremental works with dataframes

- dask_ml/model_selection/_incremental.py
- tests/model_selection/test_incremental.py
This preserves the `random_state` in `IncrementalSearchCV`'s parameter sampler. Before, the `ParameterSampler` object didn't have `random_state` specified so multiple calls to `IncrementalSearchCV` with the same random state had no effect on the parameters sampled.
**Reference issues**
* Motivating comment: https://github.com/dask/dask-ml/pull/221/files#r272723216
> BUG: make IncrementalSearchCV use random_state when sampling parameters

- dask_ml/metrics/regression.py
Currently mean_absolute_error is wrapping to mean_squared_error
> Correct doc wrap to sklearn mean_absolute_error

- docs/source/index.rst
- docs/source/joblib.rst
scikit-learn, as of 0.21.0, no longer vendors joblib which [became a dependency](https://github.com/scikit-learn/scikit-learn/blob/a243d96336cb4f50ca3635b3062a273f3dc5183a/setup.py#L231).
> DOC Joblib is no longer vendored in scikit-learn

- docs/source/contributing.rst
Minor typo fix in contributing docs. conda env filename extension is .yaml, but docs used .yml
> DOC: Fixed yaml/yml typo in contributing.rst

- dask_ml/preprocessing/data.py
- tests/preprocessing/test_data.py
Closes #562.
I'm now adding the index back on. 
I also added a test. If there's a more elegant way to reshuffle the index than `sample`, please let me know. 
I also made one of the existing tests stricter by removing a now unnecessary `reset_index=True` (https://github.com/dask/dask-ml/blob/master/tests/preprocessing/test_data.py#L568).
> [BUG] Preserve index in PolynomialFeatures

- dask_ml/_compat.py
- dask_ml/_partial.py
- dask_ml/wrappers.py
- tests/test_incremental.py
- tests/test_partial.py
This is useful for pipelines that start with non-ndarrays, e.g. text classification.
> Preserve non-arrays in partial

- dask_ml/decomposition/pca.py
- dask_ml/utils.py
- tests/test_pca.py
This PR allows Dask-ML's PCA implementation to work with NumPy arrays and Pandas DataFrames.
This PR closes #578 (well https://github.com/dask/dask-ml/issues/578#issuecomment-548973996).
> ENH: PCA works with NumPy/Pandas data

- docs/source/hyper-parameter-search.rst
Replace dask-searchcv in main dask-ml docs (but left appropriate mention in history).
> dask-searchcv -> dask-ml in docs (#585)

- docs/source/contributing.rst
**What does this PR do?**
Closes #564 and adds documentation on how to build docs.
I ran into an issue running `conda env create -f ci/environment-docs.yaml --name=dask-ml-dev-docs`, some issue with xgboost and running a `brew install` command. That issue isn't relevant here, but I sidestepped it with the mentioned method (and I believe it also performs avoids some computation).
> DOC: Adds documentation on building docs

- dask_ml/preprocessing/data.py
- tests/preprocessing/test_data.py
I ran into the issue in #357 while using DummyEncoder recently, so I figured I would contribute a small fix for the print statement.
It also adds a test with `columns=...` specified. Would any other tests be useful here?
> Fix DummyEncoder.transform error message

- dask_ml/preprocessing/data.py
- tests/preprocessing/test_data.py
Under the `Notes` section [here](https://ml.dask.org/modules/generated/dask_ml.preprocessing.StandardScaler.html#dask_ml.preprocessing.StandardScaler) it mentions:
> NaNs are treated as missing values: disregarded in fit, and maintained in transform.
To be consistent with these docs I've used `nanmean` and `nanvar` instead of the usual mean and var methods.
> use nanmean and nanvar to comply with sklearn docs

- dask_ml/model_selection/utils.py
- tests/test_model_selection.py
Fix #516.
Maybe there is a better test? Also could use `type(x).__name__` (rather than hardcoded `ndarray`) as in `client.scatter`: https://github.com/dask/distributed/blob/9b5bf448af478a166069aefc9c0c1354a29ae482/distributed/client.py#L1930
> Make GridSearchCV reuse scattered data.

- dask_ml/model_selection/_incremental.py
- dask_ml/utils.py
- tests/model_selection/test_incremental.py
It makes the conversion to Dask Array more clear. This reflects the documentation in https://github.com/dask/dask/pull/4516
**Reference issues/PRs**
* The motivation is https://github.com/dask/dask-ml/issues/628. I started to support Dataframes in `IncrementalSearchCV`. However, I'm not sure how feasible this is: `train_test_split` requires known chunk sizes.
> DOC: provide methods to circumvent unknown chunk sizes

- docs/source/examples.rst
- docs/source/incremental.rst
- docs/source/xgboost.rst
* Links to "machine learning" section of dask-examples
* Small fixes (typos, broken links)
**References issues/PRs**
* This closes #641.
* This PR depends on https://github.com/dask/dask-examples/pull/144.
> DOC: better link to dask-examples

- docs/source/contributing.rst
I just noticed the link to the sklearn estimator check was out of date. It looks like it was moved.
> Updated estimator check link in contrib docs.

- dask_ml/utils.py
- tests/linear_model/test_glm.py
It modifies message of the `TypeError` in utils.py if Dask Dataframes are not accepted. It suggests code that may resolve the issue.
I only provide `ddf.to_dask_array(...)` solutions because Pandas recommends using `to_numpy` instead of `values`: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.values.html
**Reference issues/PRs**
The motivation is https://github.com/dask/dask-ml/issues/84. I tried to get the code to fail with unknown chunk sizes, but the code worked. Instead, I decided to modify the message about not accepting Dask DataFrames with a potential solution.
(note: I make sure `fit_intercept in [True, False]` because of https://github.com/dask/dask-ml/issues/84#issuecomment-342526205).
> MAINT: provide potential solutions in warning on "dataframes not accepted"

- dask_ml/utils.py
> Import ABC from collections.abc for Python 3 compatibility.

- tests/test_incremental.py
> MAINT: in tests, don't use patch as a context manager

- docs/source/contributing.rst
Added more verbose processing of installing and building pre-commit to save people clicking through to the pre-commit project to see how to install it.
Removed the instructions of going to the dask-ml root as I assume people are working in there if they are running things like https://ml.dask.org/contributing.html#creating-an-environment
I also looked at the xarray docs for inspiration http://xarray.pydata.org/en/stable/contributing.html#code-formatting
> DOC: add install pre-commit code

- docs/source/modules/api.rst
Issue reference : https://github.com/dask/dask-ml/issues/700
This PR:
- includes dask_ml.datasets module to the API documentation
Comment:
I see a make_classification() function that is not documented. I didn't include it in this PR for this reason. Can you confirm?
> Docs: [Issue/700]: Add datasets to API documentation

- dask_ml/model_selection/_split.py
Only within-block shuffling is allowed. This is the default, regardless
of the types.
> DOC: Fixed train_test_split docs for Dask DataFrame

- dask_ml/model_selection/_incremental.py
- tests/model_selection/test_hyperband.py
- tests/model_selection/test_incremental.py
It doesn't look like we actually use exact chunk sizes anywhere, so this should be ok?
I may be wrong though.  Regardless there is probably still some cleanup to do here.  I thought I'd push up something early for feedback though.
cc @stsievert
> Support Dask Dataframes in Hyperband

- ci/environment-latest.yaml
- docs/source/contributing.rst
Closes #704 
Here is what the docs build looks like:
> DOC: add conda build instructions

- dask_ml/feature_extraction/text.py
- dask_ml/utils.py
- docs/source/modules/api.rst
- tests/feature_extraction/test_text.py
This has an implementation of CountVectorizer.
The primary difficulty is learning the vocabulary from the data. The basic idea is to just use scikit-learn's CountVectorizer on each partition of a bag. That'll give us a list of vocabularies (dictionaries) that we need to merge.
A naive implementation would just pass the `vocabularies` around as a dictionaries in the task graph. This isn't great since these can get pretty large. For the news dataset, scikit-learn learns a vocabulary that's 18 MB.
I've prototyped something using distributed's Actors (cc @mrocklin if you're interested in seeing them in use). Timings:
Actors? | fit | compute |
------- | --- | ------- |
Yes | 2.3 | 3.4     |
No | 5.2 | 4.2
I'll probably spend a bit more time to make this work without actors again. Regardless, …
> Count vectorizer (with Actors)

- ci/environment-3.6.yaml
- dask_ml/preprocessing/_encoders.py
- setup.py
- tests/preprocessing/test_encoders.py
- tests/test_incremental_pca.py
- tests/test_parallel_post_fit.py
Allows for
```python
ohe = OneHotEncoder(categories=[['a', 'b'], ['c', 'd']])
```
Previously, we required inputs to be CategoricalDtype for dataframes.
Closes https://github.com/dask/dask-ml/issues/726
> ENH: Support user categories in OneHotEncoder

- dask_ml/linear_model/glm.py
- tests/linear_model/test_glm.py
I noticed that the `dask_ml.linear_model.LogisticRegression` class lacked a `decision_function()` method like is implemented in the corresponding [scikit-learn API](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html#sklearn.linear_model.LogisticRegression.decision_function).
This PR adds a `decision_function()` method and updates one corresponding test.
> Add a 'decision_function()' method to the 'LogisticRegression' class.

- ci/environment-3.6.yaml
- ci/environment-3.7.yaml
- ci/environment-3.8.yaml
- dask_ml/_compat.py
- dask_ml/_partial.py
- dask_ml/decomposition/incremental_pca.py
- dask_ml/decomposition/pca.py
- dask_ml/decomposition/truncated_svd.py
- dask_ml/model_selection/_incremental.py
- dask_ml/model_selection/utils_test.py
- dask_ml/preprocessing/data.py
- dask_ml/utils.py
- dask_ml/wrappers.py
- tests/test_impute.py
- tests/test_incremental_pca.py
- tests/test_pca.py
- tests/test_svd.py
This is a partial fix for https://github.com/dask/dask-ml/issues/736.
I think this is probably the best approach: https://github.com/dask/dask-ml/compare/master...eric-czech:svd_flip?expand=1#diff-151bb55aba85377c700e75a189fa2256
That only fixes TruncatedSVD at the moment, but it seems like a reasonable way to account for the differences now.  A function like `flip_vector_signs` could be applied to PCA components, loadings or scores to point all the vectors in the same direction before comparing them.  I'll go forward with that and try to fix as much as I can in the current build unless you would prefer something else @TomAugspurger.
FYI this PR also removes several xfail cases that now work for short-fat arrays.
> Update svd tests for svd_flip

- dask_ml/_compat.py
- dask_ml/decomposition/incremental_pca.py
- dask_ml/utils.py
- tests/test_incremental_pca.py
- tests/test_pca.py
- tests/test_svd.py
Hey @TomAugspurger, this includes some small changes to address the wrinkle I mentioned at https://github.com/dask/dask-ml/pull/737#issuecomment-692959949.  The "u vs v" choice in `svd_flip` does depend on whether or not you plan on using the right or left singular vectors and there is no way (I can find) to correct them both simultaneously.  Ideally, all PCA functions use a "v-based" correction since the principal components are equivalent to the right singular vectors.  I chose the "u-based" correction as the default in dask though, since that's what sklearn does, which leads to the somewhat awkward scenario at this level where you have to skip the correction in dask and then apply a similar one.
It would be most convenient for this project (and what we're trying to do) if a "v-based" …
> Fixing sign stability in incremental PCA

- dask_ml/model_selection/_search.py
Over in https://github.com/dask/dask-ml/pull/754 I ran across a `FutureWarning` in the scikit-learn dev build which caused CI to fail. The `estimator._pairwise` attribute was deprecated in https://github.com/scikit-learn/scikit-learn/pull/18143 in favor of using the `"pairwise"` key in the estimator's tags dictionary.
> Update pairwise check for scikit-learn 0.24

- .github/workflows/ci-docs.yaml
setup-miniconda v2 fixes some deprecations in GitHub Actions. The project has also been moved to conda-incubator.
> Bump GHA setup-miniconda version

- dask_ml/decomposition/truncated_svd.py
Dask 2020.12.0 introduced `iteration` parameter for `da.array.linalg.svd_compressed`. This PR fixes calling this function in `truncated_svd`
> Fix passing `n_power_iter` for `da.svd_compressed`

- dask_ml/_compat.py
- dask_ml/cluster/k_means.py
- dask_ml/preprocessing/_encoders.py
- tests/model_selection/dask_searchcv/test_model_selection.py
- tests/test_impute.py
- tests/test_naive_bayes.py
> Add skip for pandas 1.2.0

- dask_ml/_compat.py
- dask_ml/model_selection/_incremental.py
The 2021.02.0 Dask / Distributed release updated how `priority=`, `resources=`, etc. keywords are handled (xref https://github.com/dask/distributed/pull/4406). This PR adds compatibility code to ensure that we use the new annotation system when using newer versions of Dask and Distributed. 
For reference, it looks like the CI failures here are due to unrelated `mypy` issuse which are being handled in https://github.com/dask/dask-ml/pull/786
> Dask annotations compatibility

- .github/workflows/ci-docs.yaml
Our built docs are put in `build/html`
https://github.com/dask/dask-ml/blob/cdd954d7a2d7f60ed50cddab788a1b30955f1baf/docs/Makefile#L9
However, our CI to deploy docs us attempting to deploy `_build/html`
https://github.com/dask/dask-ml/blob/cdd954d7a2d7f60ed50cddab788a1b30955f1baf/.github/workflows/ci-docs.yaml#L36
This PR updates our documentation GitHub action to ensure we use the correct directory 
EDIT: Closes https://github.com/dask/dask-ml/issues/790
> Fix CI for deploying docs

- setup.py
Looking through the codebase today, I noticed that `setup.py` includes a dependency on a package `pytest-cover`.
That package's most recent release was in July 2015 ([PyPI page](https://pypi.org/project/pytest-cover/)), and after that point it was merged into `pytest-cov`. Based on that information and the fact that several environment files in this repo refer to `pytest-cov` (e.g. https://github.com/dask/dask-ml/blob/c964587bedd9abf29cb3065369ccf9f437c8e3eb/ci/environment-3.8.yaml#L23), I think `pytest-cov` is the intended dependency for `dask-ml`'s tests.
This PR proposes switching that `setup.py` entry to `pytest-cov`.
> fix testing dependency in setup.py

- ci/environment-3.7.yaml
- ci/environment-3.8.yaml
- ci/environment-docs.yaml
It looks like the `dask=2021.3.0` introduced a regression which is causing tests here to fail (see [a recent CI build on the `main` branch](https://dev.azure.com/dask-dev/dask/_build/results?buildId=1983&view=logs&j=ec4c5d99-1a39-52ae-ac68-aabdfb55b8a0&t=fc02acdf-e905-55f3-d38f-f279841d296b)). Locally I tested against the latest `main` branch of `dask` and the issue seems to be resolved.
This PR temporarily applies a version constraint to `dask` in CI to get tests to pass. We should revert the changes here after the next `dask` release.
> Temporarily restrict dask version in CI

- dask_ml/_compat.py
- dask_ml/cluster/k_means.py
- dask_ml/decomposition/pca.py
- dask_ml/model_selection/_incremental.py
- dask_ml/model_selection/_search.py
- dask_ml/model_selection/_successive_halving.py
- dask_ml/preprocessing/data.py
- dask_ml/preprocessing/label.py
- dask_ml/wrappers.py
**Associated GitHub Issue(s):** N/A
**Tests/`black`/`pyflakes` passing:** Yes
**Tests added:** No
I've noticed that `check_is_fitted` is referenced differently from a couple of files in the `dask-ml` codebase.
The majority (8 vs 2) of the references are `from .._compat import check_is_fitted`.
This PR proposes unifying the references (i.e., updating the remaining 2) for the sake of future-proofing, with respect to any potential updates in the behavior of `dask_ml/compat.py`.
> Make all references to sklearn.utils.validation.check_is_fitted uniform

- setup.py
- **Associated GitHub Issue(s):** https://github.com/dask/dask-ml/issues/802.
- **Tests/`black`/`pyflakes` passing:** Yes.
- **Tests added:** No.
- **Description:** We saw over at #802 that due to a discrepancy in the underlying `numba` version, some unexpected behavior was observed. This PR proposes a minimum version requirement for `numba`, namely `0.51.0`, which is the earliest one, not enabling `dask-ml` to exhibit correct, expected behavior.
> Require numba>=0.51.0 (#802)

- docs/source/xgboost.rst
Following the discussion in https://github.com/dask/community/issues/104, the maintainers of `dask-lightgbm` agreed to upstream that project into `LightGBM`: https://github.com/microsoft/LightGBM/pull/3515.
This week, the first version of `LightGBM` that includes a Dask interface was released.
* https://pypi.org/project/lightgbm/
* https://github.com/microsoft/LightGBM/releases/tag/v3.2.0
Now that the LightGBM Dask integration has been released, this PR proposes removing references to `dask-lightgbm` and replacing them with references to LightGBM.
I've also opened https://github.com/dask/dask-lightgbm/pull/30, proposing that `dask-lightgbm` do one more release that raises a warning directing users to `LightGBM`.
> [docs] replace dask-lightgbm reference with LightGBM

- .github/workflows/docs.yaml
- ci/environment-docs.yaml
Previously we were specifying the Python version for our documentation build in two places: our GitHub actions workflow and the corresponding conda environment file. This PR switches to just using the conda environment file to avoid using inconsistent Python versions, which can lead to CI failures.
> Ensure consistent Python version in docs CI

- README.rst
- docs/source/index.rst
README preview [here](https://github.com/hristog/dask-ml/blob/update-readme-and-doc-index/README.rst).
Apparently, the Codecov report is still pointing at the `master` branch (Update: I've just raised https://github.com/dask/dask-ml/issues/817 for that to be addressed under, if needs be). The [Codecov settings](https://app.codecov.io/gh/dask/dask-ml/settings) need to be updated accordingly (requires maintainer access, unless the target brach could be set up from elsewhere).
The badges are set to point to `main`.
Update: https://github.com/dask/dask-ml/issues/817 has been closed as done.
> Update README and documentation index page

- ci/posix.yaml
I noticed today, looking at the config for this project's CI jobs, that there is a typo in `ci/posix.yaml`. The variable `SKLEARN_DEV` is used to control whether or not the latest nightly build of `scikit-learn` should be installed. Several matrix items use the variable `SKLARN_DEV` (missing an "E").
This doesn't affect the jobs at all as far as I can tell, since not being set at all and being set to `"no"` should result in the same outcome from `eq(variables.SKLEARN_DEV, 'yes')`. But I still think it's worth fixing, just for the sake of correctness and greppability.
> fix typo in CI config

- dask_ml/metrics/__init__.py
- dask_ml/metrics/regression.py
- docs/source/modules/api.rst
- tests/metrics/test_regression.py
This PR proposes adding `mean_absolute_percentage_error()` ("MAPE"), as originally suggested in #691.
It follows the implementation from `scikit-learn` (https://github.com/scikit-learn/scikit-learn/blob/9cfacf1540a991461b91617c779c69753a1ee4c0/sklearn/metrics/_regression.py#L280), including the use of `np.finfo(np.float64).eps` in the denominator to prevent divide-by-0 errors.
This PR adds a bit of test coverage by adding `mean_absolute_percentage_error()` to the `metric_pairs` fixture in tests. It would automatically get more specific coverage (like for combinations of `multioutput` and `compute`) if #820 is accepted.
Thanks for your time and consideration.
> add MAPE to regression metrics (fixes #691)

- dask_ml/metrics/regression.py
- tests/metrics/test_regression.py
Fixes #818.
Fixes #819.
* ensures that regression metrics respect `compute` argument when `multioutput == "raw_values"`
* ensures that regression metrics' treatment of `multioutput=None` matches the behavior of their scikit-learn equivalents
* removes irrelevant comment about `np.average()` in regression metrics
* adds tests on behavior of metrics for different values of `multioutput`
See the linked issues for an explanation. I believe this PR is worth accepting because it will resolve an inconsistency with `scikit-learn` and with `dask-ml` itself, but it is technically a breaking change.
Thanks for your time and consideration.
> make regression metrics 'multioutput' behavior consistent with scikit-learn (fixes #818)

- dask_ml/linear_model/glm.py
- dask_ml/linear_model/utils.py
- tests/linear_model/test_glm.py
This PR addresses #386 by making sure `LogisticRegression.predict_proba()` returns an array of shape `(n, 2)` to match what scikit-learn does. There are some things currently hard-coded for binary classification only, but it is clear that multi-class is currently not supported so that can be changed when multi-class is implemented.
There is some risk here that if users have downstream code that depends on the current functionality (return shape of `(n,)`), the changes from this PR could break their code.
> #386 LogisticRegression.predict_proba should return (n, 2) for binary

- tests/metrics/test_regression.py
This PR proposes simplifying the current tests for regression metrics and expanding the test coverage of `mean_squared_log_error()`.
As of this PR, that metric function's behavior when `multioutput=None` and `multioutput="uniform_average"` would now be tested.
> test multioutput for metrics.mean_squared_log_error()

- ci/environment-docs.yaml
This was pinned in https://github.com/dask/dask-ml/pull/807 but is no longer needed
> Unpin `dask` in documentation environment

- dask_ml/_partial.py
Closes https://github.com/dask/dask-ml/issues/877
Closes https://github.com/dask/dask/issues/8360
> Fix `Delayed` optimization issue 

- README.rst
This PR points users to our new Discourse instead of gitter (see https://github.com/dask/community/issues/194 for more discussion around this topic). Similar to https://github.com/dask/dask/pull/8332 and https://github.com/dask/distributed/pull/5489. 
cc @ian-r-rose 
EDIT: Note that CI failures are unrelated and being addressed in https://github.com/dask/dask-ml/pull/878
> Point users to Discourse

- setup.cfg
Similar to https://github.com/dask/dask/pull/8090 and https://github.com/dask/distributed/pull/5276. This will result in color coded output in CI (similar to what many folks see when running tests locally)
> Add pytest color to CI

- docs/source/modules/api.rst
Got a little confused reading the docs until I realized `StandardScaler` is listed twice. Fixing it here!
> DOC: typo, `StandardScaler` listed twice in docs

- docs/source/changelog.rst
- setup.py
* Changelog
* Update requirements (#862 requires NumPy 1.20 for the new `like=` keyword)
> RLS: 2016.11.16

- .github/workflows/upstream.yml
- ci/install.sh
There was a recent issue where a `dask` release broke `dask-ml` (xref https://github.com/dask/dask-ml/issues/870). This issue has since been fixed, but it would be nice to catch these types of breakages before an upstream dependency releases. To help increase visibility, this PR proposes we add a new `upstream` CI build, which is very similar to [the one used in Dask's CI](https://github.com/dask/dask/blob/43f33a32dd5cdf77363b6ff6348b5f1a8282d28c/.github/workflows/upstream.yml), to run the `dask-ml` test suite against the latest development version of a few key upstream dependencies.
In order to not fully block CI for `dask-ml` when an upstream CI failure occurs, this PR proposes we only run the upstream build on:
- Pushes to the `main` branch
- A nightly cron job (against the current …
> Add upstream CI build

- dask_ml/_compat.py
- dask_ml/_partial.py
- dask_ml/model_selection/methods.py
- dask_ml/model_selection/utils.py
- dask_ml/preprocessing/data.py
- tests/linear_model/test_glm.py
Fixes #895.
Updated the `fit` method in the `_partial` module to specify the layer during delayed object creation as required after dask/dask#8452. 
Also added a commit unrelated to the issue replacing the usage of `distutils.version.LooseVersion` with `packaging.version.parse` as a side effect of needing it while testing locally. Happy to remove it or open a separate pr for those changes if preferred.
> Specify HLG layer name during delayed object creation in fit

- dask_ml/model_selection/_search.py
- tests/model_selection/dask_searchcv/test_model_selection_sklearn.py
Attempting to resolve the breakage recorded in https://github.com/dask/dask-ml/issues/894
> Skip `_check_param_grid` import for scikit-learn > 1.0.2

- dask_ml/model_selection/_search.py
Dear maintainers,
this pull request replaces the import of `_is_pairwise` with the import of `_is_pairwise_metric` for compatibility with scikit-learn 1.1 (hopefully to be released soon). About backward compatibility: `_is_pairwise` was deprecated in 0.24 (December 2020).
Fixes #908.
Thanks for considering it.
> Replace _is_pairwise import with _is_pairwise_metric for compatibility with scikit-learn 1.1

- dask_ml/model_selection/_search.py
@TomAugspurger sorry to bother you again.
I realized that one of the failures in #910 was indeed related to my changes.
The failure is related to #771 and its fix in  #772.
As the tag "pairwise" is not defined the test fails again.
I have replaced ``is_pairwise_metric`` with the ``_safe_tags()`` function (see [here](https://github.com/scikit-learn/scikit-learn/blob/e61040c14e59bec3b0d275d40a43e10cf641af32/sklearn/utils/_tags.py#L25)) which falls back to default when the tags is not defined.
Sorry for not noticing that before.
> Fix precomputed kernel test with _safe_tags.

- ci/environment-docs.yaml
- docs/source/conf.py
On Monday, June 6th, dask.org will go live with a new design (see https://github.com/dask/community/issues/220). This PR is in preparation for the theme update for `dask-sphinx-theme` and can be merged in *after* https://github.com/dask/dask-sphinx-theme/pull/67 on Monday.
cc @jacobtomlinson @jsignell
> Update docs theme for rebranding

- docs/source/index.rst
Typo fixes to add some new lines. :)
After change:
> Fix toctree to display "Get Started" section in the left sidebar

- ci/environment-3.10.yaml
- ci/environment-3.8.yaml
- ci/environment-3.9.yaml
- ci/environment-docs.yaml
- dask_ml/cluster/k_means.py
- dask_ml/cluster/spectral.py
- dask_ml/decomposition/incremental_pca.py
- dask_ml/decomposition/pca.py
- dask_ml/preprocessing/_encoders.py
- setup.py
- tests/compose/test_column_transformer.py
- tests/linear_model/test_glm.py
- tests/model_selection/dask_searchcv/test_model_selection_sklearn.py
- tests/model_selection/test_hyperband.py
- tests/preprocessing/test_encoders.py
- tests/test_kmeans.py
- tests/test_parallel_post_fit.py
- tests/test_pca.py
> updates for scikit-learn 1.2.0

- ci/environment-docs.yaml
- ci/environment-latest.yaml
- dask_ml/compose/__init__.py
- dask_ml/decomposition/extmath.py
- dask_ml/feature_extraction/__init__.py
- dask_ml/feature_extraction/text.py
- dask_ml/linear_model/__init__.py
- dask_ml/linear_model/utils.py
- dask_ml/metrics/pairwise.py
- dask_ml/model_selection/__init__.py
- dask_ml/model_selection/_split.py
- dask_ml/preprocessing/__init__.py
- dask_ml/wrappers.py
- dask_ml/xgboost.py
- tests/compose/test_column_transformer.py
- tests/linear_model/test_glm.py
- tests/metrics/test_metrics.py
- tests/metrics/test_regression.py
- tests/model_selection/dask_searchcv/test_model_selection_sklearn.py
- tests/model_selection/test_incremental.py
- tests/model_selection/test_split.py
- tests/preprocessing/test_data.py
- tests/test_incremental_pca.py
- tests/test_kmeans.py
- tests/test_normalize.py
- tests/test_pca.py
- tests/test_svd.py
Opening a quick PR to update the environment yamls for Python 3.11 and fix some linting errors. Looks like the test matrix already includes 3.11. 
closes #970
> Python 3.11 Updates

- .github/workflows/release.yaml
Previous one failed
https://github.com/dask/dask-ml/actions/runs/8516080288
Trying out the trusted publisher thing.
> Fixed release workflow

- .github/workflows/release.yaml
This `if` condition shouldn't be necessary. We only run this workflow on releases.
> Updated conditions on release workflow

- tests/test_svd.py
This previously deprecated attribute has been definitly removed from scipy in the latest release (1.14.0).
It is equivalent to `.toarray()`.
https://github.com/scipy/scipy/blob/7750f15ffd026ab758bd9b720f3628b0284cb905/doc/source/release/1.14.0-notes.rst?plain=1#L225-L228
> Fixed: stop using invalid .A attribute of scipy sparse matrix

- .github/workflows/lint.yaml
- .github/workflows/tests.yaml
- .github/workflows/upstream.yml
- ci/environment-3.10.yaml
- ci/environment-3.11.yaml
- ci/environment-3.12.yaml
- ci/environment-3.13.yaml
- ci/environment-3.9.yaml
- ci/environment-docs.yaml
- dask_ml/base.py
- dask_ml/impute.py
- dask_ml/linear_model/utils.py
- dask_ml/model_selection/_incremental.py
- dask_ml/model_selection/_search.py
- dask_ml/preprocessing/_encoders.py
- dask_ml/preprocessing/data.py
- dask_ml/utils.py
- docs/source/changelog.rst
- pyproject.toml
- tests/conftest.py
- tests/ensemble/test_blockwise.py
- tests/model_selection/dask_searchcv/test_model_selection.py
- tests/model_selection/test_split.py
- tests/preprocessing/test_data.py
- tests/preprocessing/test_label.py
- tests/test_incremental_pca.py
- tests/test_kmeans.py
- tests/test_parallel_post_fit.py
Towards https://github.com/dask/dask-ml/issues/1007
There are still some test failures here. I'll need to look closer, but it looks like they may all be either unrelated to upgrading Dask (e.g. https://github.com/dask/dask-ml/issues/1006) or already have a fix in flight (e.g. https://github.com/dask/dask-ml/pull/1004) 
Given the `dask` / `distributed` / `numpy` / `pandas` version bumps, there's a lot more compatibility code we could also remove. Holding off on that now to focus on getting tests passing. 
cc @TomAugspurger for thoughts
> [WIP] Upgrade to latest Dask 

- dask_ml/metrics/regression.py
- tests/metrics/test_regression.py
Closes https://github.com/dask/dask-ml/issues/1012
First PR here. Curious to hear your feedback.
**Problem**
After updating to Dask 2025.2.0, tests fail with a ValueError due to changes in chunk size handling.
**Solution**
Refactor r2_score() to use da.where() for correct broadcasting.
**Testing**
Test added to ensure r2_score() works correctly with arrays that have different chunk configurations.
> fix: prevent broadcasting errors in r2_score using da.where()
