- daskml/base.py
- daskml/linear_model/__init__.py
- daskml/linear_model/passive_aggressive.py
- daskml/linear_model/perceptron.py
- daskml/linear_model/stochastic_gradient.py
- daskml/naive_bayes.py
- daskml/neural_network.py
- daskml/util.py
- tests/conftest.py
- tests/linear_model/test_neural_network.py
- tests/linear_model/test_passive_aggressive.py
- tests/linear_model/test_perceptron.py
- tests/linear_model/test_stochastic_gradient.py
- tests/test_naive_bayes.py
All of classification and regression from http://scikit-learn.org/stable/modules/scaling_strategies.html
> Wrap more partial_fits

- daskml/cluster/__init__.py
- daskml/cluster/minibatch.py
- daskml/datasets.py
- tests/conftest.py
- tests/test_minibatch.py
This depends on a modification to dask.array.learn to make `y` optional
> Wrap MiniBatchKMeans

- setup.py
While trying to run the tests I noticed that we need scipy and it wasn't in setup.py.
> Added scipy to setup.py

- .gitignore
- benchmarks/base.py
- benchmarks/k_means_kdd.py
- benchmarks/kmeans_airline.py
- ci/install-travis.sh
- ci/requirements_dev.txt
- daskml/cluster/__init__.py
- daskml/cluster/_k_means.pyx
- daskml/cluster/k_means.py
- daskml/metrics/__init__.py
- daskml/metrics/pairwise.py
- daskml/utils.py
- docs/source/clustering.rst
- docs/source/index.rst
- docs/source/modules/api.rst
- setup.cfg
- setup.py
- tests/conftest.py
- tests/test_kmeans.py
- tests/test_metrics.py
The benchmarks are still a WIP.
> ENH: Adds K-Means

- .circleci/config.yml
- ci/environment-circle.yml
- daskml/base.py
- daskml/cluster/__init__.py
- daskml/cluster/k_means.py
- daskml/cluster/minibatch.py
- daskml/linear_model/__init__.py
- daskml/linear_model/passive_aggressive.py
- daskml/linear_model/perceptron.py
- daskml/linear_model/stochastic_gradient.py
- daskml/naive_bayes.py
- daskml/neural_network.py
- daskml/preprocessing/data.py
- docs/source/modules/api.rst
- docs/source/single-machine.rst
- tests/linear_model/test_neural_network.py
- tests/linear_model/test_passive_aggressive.py
- tests/linear_model/test_perceptron.py
- tests/linear_model/test_stochastic_gradient.py
- tests/test_metrics.py
- tests/test_minibatch.py
- tests/test_naive_bayes.py
The Big* names were a joke :) Renaming to `Parital*`, since that hints at what happens. Added more docs and a section in single-machine.
> Big rename

- docs/source/index.rst
I'm walking through the dask-ml docs.   Starting here are mostly copy-editing things.
> Add copy-edit changes to index

- ci/environment-circle.yml
- setup.py
- tests/test_model_selection.py
Depends on https://github.com/dask/dask-searchcv/pull/60
> ENH: Wrap dask-searchcv

- ci/environment.yml
> More environment updates

- dask_ml/cluster/k_means.py
Seems to help the task scheduler in some situations
Closes https://github.com/dask/dask-ml/issues/39
> PERF: Sort indexes before slicing

- dask_ml/cluster/k_means.py
- tests/test_kmeans.py
Added the ability to initialize clusters randomly.
Refactored k_init to be a general function that dispatches to a dedicated
initialization method.
> ENH/REF: Added 'random' init

- dask_ml/cluster/k_means.py
- tests/test_kmeans.py
Dask.Dataframe raises, since lengths are unknown.
> Handle numpy arrays and pandas dataframes in k-means

- LICENSE.txt
> PKG: added license

- docs/source/index.rst
- docs/source/install.rst
- setup.py
(We don't actually have conda-forge packages or wheels up yet)
> Doc install

- dask_ml/cluster/k_means.py
- dask_ml/datasets.py
- dask_ml/utils.py
- setup.cfg
- setup.py
- tests/preprocessing/test_data.py
- tests/test_kmeans.py
- tests/test_utils.py
> Datasets wraps

- docs/source/install.rst
I had some issues getting the optional dependencies sorted out in the conda recipe https://github.com/conda-forge/staged-recipes/pull/4229
> DOC: Update install notes about extras

- dask_ml/cluster/k_means.py
- tests/test_kmeans.py
Closes https://github.com/dask/dask-ml/issues/79
> BUG: Handle random state for all initializers

- dask_ml/model_selection.py
- dask_ml/xgboost.py
- docs/source/modules/api.rst
> Updated notes on scalability of various estimators

- readthedocs.yml
> MAINT the environment filename for readthedocs

- dask_ml/preprocessing/data.py
- docs/source/contributing.rst
- docs/source/preprocessing.rst
Minor changes affecting the documentation.
> Fixing typos in the first pages of the documentation (contributing and preprocessing)

- dask_ml/cluster/spectral.py
Computing the upper-left block was taking a while since we didn't persist
the small block before doing pairwise distances.
> PERF: Some scalability fixes

- dask_ml/linear_model/glm.py
- tests/linear_model/test_glm.py
> BUG: Allow unknown chunks in GLMs

- docs/source/_static/style.css
- docs/source/conf.py
This follows on https://github.com/dask/dask/pull/3360
> Add style sheet

- docs/source/changelog.rst
> DOC: Added 0.5 release notes

- dask_ml/preprocessing/data.py
- docs/source/changelog.rst
- tests/preprocessing/test_data.py
> Convert dask.dataframe to dask.array when using StandardScaler.fit()

- dask_ml/datasets.py
- docs/source/changelog.rst
- tests/conftest.py
- tests/test_datasets.py
- tests/test_kmeans.py
- tests/test_naive_bayes.py
- tests/test_parallel_post_fit.py
- tests/test_spectral_clustering.py
- tests/test_utils.py
Change the methods in dask_ml.datasets to not overwhelm a single
machine when generating large random datasets.
Closes #67
> REF: Large dataset generators

- dask_ml/utils.py
- tests/test_utils.py
xref https://github.com/dask/dask-ml/issues/180
> Error message for check_array chunks error

- dask_ml/model_selection/_split.py
- tests/model_selection/test_split.py
This is an abstract method in the base class that I missed.
> API: Add get_n_splits

- .circleci/config.yml
- ci/release.py
- docs/source/contributing.rst
- setup.py
- tests/test_incremental.py
This PR adds a "Running tests" section to the contributing docs, along with a few other minor edits.
> Updates contributing docs

- dask_ml/_partial.py
- tests/test_partial.py
This PR implements and tests
* creating dask arrays if the input args are np.ndarrays (with 1 chunk of the same shape) for both `fit` and `predict`
* having `predict` return the same type as the argument passed in
This generalizes to `Incremental` because it calls `fit`.
> MAINT: accept ndarrays for input to fit and predict

- dask_ml/model_selection/_split.py
Closes https://github.com/dask/dask-ml/issues/230
> BUG: Dtype for random seeds

- dask_ml/wrappers.py
- docs/source/incremental.rst
- tests/test_parallel_post_fit.py
Closes https://github.com/dask/dask-ml/issues/205
> DOC: Importance of scoring

- dask_ml/_partial.py
- tests/test_partial.py
This reverts commit 5db49e97b161a5ff3fc21a34e7b6c75a6a7a6752.
As per the decision in https://github.com/dask/dask-ml/pull/225#issuecomment-400016328
> Revert "MAINT: accept ndarrays for input to fit and predict (#224)"

- ci/environment-2.7.yml
- ci/environment-3.6.yml
> Remove sphinx gallery from env

- dask_ml/wrappers.py
- tests/test_incremental.py
Closes https://github.com/dask/dask-ml/issues/271
> BUG: Set incremental.estimator_ to the fitted estimator

- dask_ml/preprocessing/data.py
- tests/preprocessing/test_data.py
> Fixes #301

- ci/environment-2.7.yml
- ci/environment-3.6.yml
- dask_ml/wrappers.py
- docs/source/changelog.rst
- docs/source/incremental.rst
- setup.py
- tests/test_incremental.py
> Use our scorers for default score methods in Incremental

- dask_ml/linear_model/utils.py
- setup.cfg
- tests/linear_model/test_glm.py
> Added intercept with unknown chunks

- setup.py
> Specify lower bounds

- dask_ml/preprocessing/label.py
> Fixed CI failures in label encoder

- .gitignore
- dask_ml/model_selection/_search.py
- setup.cfg
- tests/linear_model/test_neural_network.py
- tests/linear_model/test_stochastic_gradient.py
- tests/metrics/test_metrics.py
- tests/model_selection/dask_searchcv/test_model_selection.py
- tests/model_selection/dask_searchcv/test_model_selection_sklearn.py
- tests/preprocessing/test_label.py
- tests/test_incremental.py
- tests/test_parallel_post_fit.py
Addresses a piece of #263
This PR elevates warnings to errors.
> [MRG] Elevates scikit-learn warnings to errors

- .circleci/config.yml
- dask_ml/model_selection/_search.py
- dask_ml/model_selection/methods.py
- dask_ml/model_selection/utils_test.py
- setup.cfg
- tests/model_selection/dask_searchcv/test_model_selection.py
- tests/model_selection/dask_searchcv/test_model_selection_sklearn.py
- tests/test_pca.py
> Fit score failure

- dask_ml/model_selection/__init__.py
- dask_ml/model_selection/_split.py
- tests/model_selection/test_split.py
Addresses some of #269 by adding `KFold`
> [MRG] Adds KFold

- ci/environment-2.7.yml
- ci/environment-3.6.yml
- docs/source/changelog.rst
- docs/source/modules/api.rst
- setup.cfg
> DOC/PKG: Prepare for 0.9 release [ci skip]

- dask_ml/model_selection/_split.py
- dask_ml/utils.py
- docs/source/changelog.rst
- setup.cfg
- tests/conftest.py
- tests/model_selection/test_split.py
- tests/test_utils.py
Closes https://github.com/dask/dask-ml/issues/351
> ENH: Support dask dataframe in train_test_split

- dask_ml/wrappers.py
- docs/source/changelog.rst
- tests/test_parallel_post_fit.py
Closes https://github.com/dask/dask-ml/issues/376
> Auto-rechunk input arrays

- dask_ml/impute.py
- docs/source/changelog.rst
- tests/test_impute.py
Closes https://github.com/dask/dask-ml/issues/385
> Fixed SimpleImputer most_frequent with dask dataframe

- dask_ml/compose/_column_transformer.py
- tests/compose/test_column_transformer.py
> Filter warning from dask dataframe concat

- docs/source/changelog.rst
- docs/source/incremental.rst
Prepping for the release (apparently it's 0.11.0, I thought it was 0.10.0, so I moved a couple).
> DOC: update changelog

- docs/source/preprocessing.rst
It's a very small correction, I hope it's useful.
> DOC: Correct small typo in preprocessing.rst

- docs/source/joblib.rst
> Updated joblib.rst

- dask_ml/model_selection/utils.py
> update indexable() to just yield dask dataframes (issue #324)

- dask_ml/cluster/k_means.py
Fixes https://github.com/dask/dask-ml/issues/378
Patch as proposed by @TomAugspurger in that issue.
> Fix  #378: high is out of bounds for int32 for k_means

- .circleci/config.yml
- ci/environment-3.6.yml
This PR updates our CI to use scikit-learn's nightly wheel instead of building it from `master`
Closes #473
> Use scikit-learn nightly wheel in CI

- dask_ml/model_selection/_split.py
> Fixed documentation typos.

- dask_ml/model_selection/_split.py
- tests/model_selection/dask_searchcv/test_model_selection_sklearn.py
- tests/test_incremental.py
- tests/test_spectral_clustering.py
Closes https://github.com/dask/dask-ml/issues/488
> COMPAT: compat with sklearn master

- dask_ml/impute.py
- tests/test_impute.py
xref https://github.com/dask/dask-ml/issues/494.
This gets our CI running again. Leaving that issue open to actually implement.
> Handle SimpleImputer add_indicator

- dask_ml/model_selection/_split.py
- tests/model_selection/test_split.py
Fixes https://github.com/dask/dask/issues/4529
> Make sure train/test_size add up to one in train_test_split

- tests/model_selection/dask_searchcv/test_model_selection_sklearn.py
> Compat for sklearn dev return_train_scores

- ci/environment-docs.yaml
- docs/source/changelog.rst
- docs/source/conf.py
Pinning sphinx to 1.8.5. May close https://github.com/dask/dask-ml/issues/512
> General doc fixups

- dask_ml/preprocessing/_encoders.py
- dask_ml/preprocessing/data.py
- tests/compose/test_column_transformer.py
Closes https://github.com/dask/dask-ml/issues
> Compat with sklearn-dev

- .gitignore
- .travis.yml
- docs/source/changelog.rst
> DOC: update changelog.

- dask_ml/_compat.py
- dask_ml/preprocessing/data.py
- tests/preprocessing/test_data.py
https://stackoverflow.com/questions/57048239/valueerror-using-dask-quantiletransformer-unknown-shape-1-nan
> Handle DataFrame in QuantileTransformer

- setup.py
> Add dask.dataframe as dependency

- dask_ml/model_selection/_search.py
- dask_ml/model_selection/_split.py
- dask_ml/model_selection/methods.py
- dask_ml/model_selection/utils.py
- setup.cfg
- tests/model_selection/dask_searchcv/test_model_selection.py
- tests/model_selection/test_split.py
It didn't provide guidance to the user anyway.
Closes https://github.com/dask/dask-ml/issues/550
> Remove warning in train_test_split

- dask_ml/cluster/k_means.py
- dask_ml/utils.py
- tests/test_kmeans.py
Closes https://github.com/dask/dask-ml/issues/551
> BUG: Handle length-0 chunks

- dask_ml/_compat.py
- dask_ml/linear_model/stochastic_gradient.py
- dask_ml/metrics/scorer.py
- dask_ml/model_selection/_incremental.py
- dask_ml/model_selection/_search.py
- dask_ml/preprocessing/data.py
- dask_ml/preprocessing/label.py
- tests/model_selection/dask_searchcv/test_model_selection.py
- tests/model_selection/dask_searchcv/test_model_selection_sklearn.py
> CI: sklearn dev

- dask_ml/model_selection/_hyperband.py
**What does this PR do?**
Adds a citation for `HyperbandSearchCV`.
**Checklist**
> DOC: adds citation for HyperbandSearchCV

- dask_ml/cluster/k_means.py
Resolve a strange issue with importing KMeans and closes #576.
This resolves the issue on my machine. I used the solution from https://github.com/numba/numba/issues/4751#issuecomment-546857245.
I would imagine this behavior is tested by https://github.com/dask/dask-ml/blob/68649550fa427eb53094b605327cfec927a46cb9/tests/test_kmeans.py#L20
> Resolves crashing on while importing KMeans

- ci/environment-3.6.yaml
- dask_ml/_compat.py
- dask_ml/feature_extraction/text.py
- dask_ml/metrics/classification.py
- dask_ml/preprocessing/data.py
- setup.py
- tests/feature_extraction/test_text.py
- tests/metrics/test_classification.py
- tests/model_selection/test_split.py
- tests/preprocessing/test_data.py
- tests/preprocessing/test_encoders.py
- tests/test_incremental.py
- tests/test_kmeans.py
> BUG: Fixed meta for FeatureHashing

- docs/source/conf.py
- docs/source/examples.rst
They're handled in dask-examples.
> DOC: remove examples

- dask_ml/_compat.py
- dask_ml/cluster/_compat.py
- dask_ml/model_selection/_incremental.py
Closes https://github.com/dask/dask-ml/issues/597
> sklearn compat

- dask_ml/_compat.py
- dask_ml/metrics/pairwise.py
- dask_ml/metrics/regression.py
- tests/model_selection/dask_searchcv/test_model_selection.py
This addresses a couple issues on dask & distributed master
- removal of docs_wraps: https://github.com/dask/dask/pull/5871/files
- `gen_with_timeout` -> `asyncio.wait_for` (https://github.com/dask/distributed/pull/3372/files).
cc @jrbourbeau, I suspect the changes needed in https://github.com/dask/dask-ml/commit/3309b33255c55b98dc707ce37f86dc7dcf8dafcf fall under "expected changes", but just to confirm.
> Compatibility Fixups

- dask_ml/model_selection/utils.py
- tests/model_selection/dask_searchcv/test_model_selection.py
Adds Dask DataFrame support to GridSearchCV.
> Add dask dataframe to gridsearchcv

- dask_ml/datasets.py
- tests/test_datasets.py
> make_classification as dask.DataFrame

- dask_ml/__init__.py
- dask_ml/model_selection/_normalize.py
- setup.cfg
- tests/test_normalize.py
> Normalize fixup

- dask_ml/model_selection/_incremental.py
In https://github.com/dask/dask-examples/pull/149/, @ToddMorrill had an error while initializing a model. However, he couldn't see the traceback. This PR resolves that.
**Reference issues/PRs**
Motivation is https://github.com/dask/dask-examples/pull/149/
> BUG: clearly show error message while initing models

- ci/environment-3.6.yaml
- ci/environment-3.7.yaml
- ci/environment-3.8.yaml
- ci/environment-docs.yaml
- ci/posix.yaml
- dask_ml/_compat.py
- dask_ml/cluster/_compat.py
- dask_ml/cluster/k_means.py
- dask_ml/decomposition/pca.py
- dask_ml/decomposition/truncated_svd.py
- dask_ml/impute.py
- dask_ml/linear_model/utils.py
- dask_ml/model_selection/_search.py
- dask_ml/preprocessing/_encoders.py
- dask_ml/preprocessing/data.py
- dask_ml/utils.py
- setup.py
- tests/linear_model/test_passive_aggressive.py
- tests/linear_model/test_stochastic_gradient.py
- tests/model_selection/dask_searchcv/test_model_selection.py
- tests/model_selection/dask_searchcv/test_model_selection_sklearn.py
- tests/model_selection/test_incremental.py
- tests/test_incremental.py
- tests/test_kmeans.py
- tests/test_normalize.py
- tests/test_pca.py
> CI: Added 3.8

- dask_ml/cluster/k_means.py
- Put the changes behind the old information to not destroy old processing pipelines (if there are any)
> Log amount of found clusters in kmeans init

- docs/source/contributing.rst
> update doc instructions

- dask_ml/metrics/regression.py
- tests/metrics/test_regression.py
> ENH: add squared option to mse

- dask_ml/feature_extraction/text.py
- tests/feature_extraction/test_text.py
Closes https://github.com/dask/dask-ml/issues/712
> Fixed vocabulary length for remote vocabulary

- tests/model_selection/test_hyperband.py
- tests/model_selection/test_incremental.py
While writing Dask-ML model selection tests, I blindly copy/pasted old code with `timeout=1000` or `timeout=5000`. This PR removes those statements.
**Reference issues/PR**
This will close (most of) #718
> TST MAINT: reduce timeout

- dask_ml/model_selection/_split.py
- tests/model_selection/test_split.py
Allow to use more array with more than 2 dimensions as input
This should resolve https://github.com/dask/dask-ml/issues/721.
> add params ensure_2d and allow_nd to check_array

- dask_ml/metrics/__init__.py
- dask_ml/metrics/regression.py
- docs/source/modules/api.rst
- tests/metrics/test_regression.py
Added mean squared log error to the regression metrics.
Used https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/metrics/_regression.py#L354 as a template
> ENH: add mean_squared_log_error

- dask_ml/decomposition/truncated_svd.py
- tests/test_svd.py
> Add compute flag to TruncatedSVD

- dask_ml/naive_bayes.py
- docs/source/index.rst
- docs/source/modules/api.rst
- docs/source/naive-bayes.rst
This PR closes #759 by adding documentation for Naive Bayes models
> add docs page and API reference entry for Naive Bayes

- dask_ml/cluster/_compat.py
- dask_ml/cluster/k_means.py
- dask_ml/model_selection/utils_test.py
- dask_ml/utils.py
- tests/test_kmeans.py
> Fix importing `dask_ml.cluster` with scikit-learn = 0.24.0

- dask_ml/wrappers.py
> Fix output dtype of PCA ParallelPost transform

- dask_ml/model_selection/_search.py
> Use `_is_pairwise` with SK024

- .github/workflows/ci-docs.yaml
- README.rst
- azure-pipelines.yml
- ci/posix.yaml
- dask_ml/_typing.py
- dask_ml/model_selection/utils.py
- dask_ml/model_selection/utils_test.py
- dask_ml/preprocessing/_encoders.py
- dask_ml/preprocessing/data.py
- docs/source/contributing.rst
- docs/source/index.rst
- tests/preprocessing/test_encoders.py
closes #784 
Hmmm. Maybe I should have based this off of #782 so that the ci would run....
> Numpy 1.20 compatibility fixes

- dask_ml/_typing.py
- dask_ml/metrics/pairwise.py
- dask_ml/metrics/regression.py
- dask_ml/preprocessing/_block_transformer.py
- dask_ml/preprocessing/_encoders.py
- dask_ml/preprocessing/data.py
- dask_ml/preprocessing/label.py
> Mypy fixes

- docs/source/changelog.rst
> RLS: v1.9.0

- .github/workflows/docs.yaml
Closes https://github.com/dask/dask-ml/issues/854
> Fetch all history for all branches and tags to determine correct version

- dask_ml/wrappers.py
- tests/test_incremental.py
- tests/test_parallel_post_fit.py
This PR resolves https://github.com/dask/dask-ml/issues/888
Todo:
> [REVIEW] Add meta inference for `ParallelPostFit.predict` for sparse arrays

- setup.py
This is a small follow-up to https://github.com/dask/dask-ml/pull/863
Closes https://github.com/dask/dask-ml/issues/942
> Update `python_requires` to be Python 3.7+
